package fr.ludiv.entities;
// Generated 15 f�vr. 2022 � 10:30:38 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private long productId;
	private Users users;
	private String name;
	private String description;
	private Long price;
	private Long stock;
	private String image;
	private Date createdAt;

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

	public Product(long productId, Users users, String name, String description, Long price, Long stock, String image,
			Date createdAt) {
		this.productId = productId;
		this.users = users;
		this.name = name;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.image = image;
		this.createdAt = createdAt;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public Long getStock() {
		return this.stock;
	}

	public void setStock(Long stock) {
		this.stock = stock;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
