package fr.ludiv.entities;
// Generated 15 f�vr. 2022 � 14:10:31 by Hibernate Tools 5.5.7.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product",schema = "public")
public class Product implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long productId;
	
	private String name;
	private String description;
	private Long price;
	private Long stock;
	private String image;
	private Date createdAt;
	private String userId;

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

	public Product(long productId, String name, String description, Long price, Long stock, String image,
			Date createdAt, String userId) {
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.image = image;
		this.createdAt = createdAt;
		this.userId = userId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public Long getStock() {
		return this.stock;
	}

	public void setStock(Long stock) {
		this.stock = stock;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
